
"""assingment.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sesMgRntlnnp45OfI_1xqQt6joNZ1aNZ
"""

#Python Program to Find the perimeter of a cylinder

# Function to calculate
# the perimeter of a cylinder
def perimeter( diameter, height ) :
    return 2 * ( diameter + height )

# Driver function
diameter = 5 ;
height = 10 ;
print ("Perimeter = ",
            perimeter(diameter, height))

# area of tetrahedron
import math

def area_of_tetrahedron(side):

    return (math.sqrt(3) * (side * side))

# Driver Code
side = 3;
print("Area of Tetrahedron =",
    area_of_tetrahedron(side));

#Program for Common Divisors of Two Numbers
a = 12
b = 24
n = 0

for i in range(1, min(a, b)+1):
    if a%i==b%i==0:
        n+=1

print(n)
